name: iOS-ipa-build

on:
  push:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Flutter deps
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update
        working-directory: ios

      - name: Copy CastarSDK.framework
        run: |
          mkdir -p ios/Frameworks
          cp -R ios/Frameworks/CastarSDK.framework ios/Frameworks/

      - name: Inject linker config
        run: |
          echo 'FRAMEWORK_SEARCH_PATHS=$(SRCROOT)/Frameworks' >> ios/Flutter/Generated.xcconfig
          echo 'OTHER_LDFLAGS=$(inherited) -framework CastarSDK' >> ios/Flutter/Generated.xcconfig

      - name: Build unsigned IPA
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Automated unsigned build"
