name: iOS-ipa-build

on:
  push:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Flutter deps
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update
        working-directory: ios

      - name: Inject linker config
        run: |
          echo 'FRAMEWORK_SEARCH_PATHS=$(SRCROOT)/Frameworks' >> ios/Flutter/Generated.xcconfig
          echo 'OTHER_LDFLAGS=$(inherited) -framework CastarSDK' >> ios/Flutter/Generated.xcconfig

      - name: Build unsigned IPA
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
          mv FlutterIpaExport.ipa ../../../
          cd ../../../

      - name: Upload IPA
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Automated unsigned build"
